Repository mozilla/MozDef, pull requests merged in 2018-11, with the labels that each got.

#926 Add Kibana URL environment variable for Meteor
  cloudy_mozdef/cloudformation/mozdef-instance.yml
Labels: cloud

#950 Update docker requirements closes #949
  docs/source/demo.rst
Labels: category:doc

#927 Make cloudy mozdef Makefile catch missing secrets
  cloudy_mozdef/Makefile
Labels: cloud

#959 Logincounts fix
  docker/compose/docker-compose-rest.yml
  docker/compose/docker-compose-sampledata.yml
  examples/demo/sampleevents/events-logins-failure.json
  examples/demo/sampleevents/events-logins-success.json
  meteor/client/logincounts.js
  meteor/server/methods.js
  rest/index.py
  rest/plugins/auth0_logincounts.py
  tests/loginput/loginput_index.conf
  tests/loginput/loginput_test_suite.py
  tests/rest/rest_index.conf
  tests/rest/rest_test_suite.py
  tests/rest/test_rest_index.py
Labels: category:enhancement, priority:medium

#972 correct the license, fixes #969
  mozdef_util/LICENSE
Labels: category:bug, category:doc

#973 pull ip from an occasionally present list
  mq/plugins/guardDuty.py
Labels: category:enhancement, cloud

#985 user_id doesn't always exist
  cron/auth02mozdef.py
Labels: category:bug
