Repository mozilla/MozDef, pull requests merged in 2019-01, with the labels that each got.

#1030 anchor a scheduling section for reference/linking
  docs/source/alert_development_guide.rst
Labels: category:doc, priority:low

#1039 Remove duplicate config key in duo log cron script
  cron/duo_logpull.py
Labels: category:bug

#1047 Fixup filterlog mq plugin
  mq/plugins/filterlog.py
  tests/mq/plugins/test_filterlog.py
Labels: category:bug

#1043 Add sample dashboards in docker
  docker/compose/mozdef_bootstrap/Dockerfile
  docker/compose/mozdef_bootstrap/files/dashboards/all_events_area.json
  docker/compose/mozdef_bootstrap/files/dashboards/category_pie_graph.json
  docker/compose/mozdef_bootstrap/files/dashboards/destinationip_bar_graph.json
  docker/compose/mozdef_bootstrap/files/dashboards/sample_dashboard.json
  docker/compose/mozdef_bootstrap/files/dashboards/sourceip_bar_graph.json
  docker/compose/mozdef_bootstrap/files/initial_setup.py
Labels: category:enhancement

#1024 Hostname search
  meteor/client/mozdef.js
Labels: category:enhancement

#1016 ipsearch addition to ipmenu dropdown
  meteor/client/layout.js
  meteor/client/mozdef.js
  meteor/server/methods.js
Labels: category:enhancement

#990 deduplicating get_aws_credentials function
  mq/common.py
  mq/esworker_sns_sqs.py
  mq/esworker_sqs.py
Labels: category:enhancement
