Repository mozilla/MozDef, pull requests merged in 2019-04, with the labels that each got.

#1182 Remove doc_type from alerts
  alerts/lib/alerttask.py
Labels: Doc_type Removal

#1200 lowercase TAGS in squidFixup.py
  mq/plugins/squidFixup.py
  tests/mq/plugins/test_squidFixup.py
Labels: category:bug

#1114 [WIP] Remove doc_type from cron
  cron/collectAttackers.py
  cron/correlateUserMacAddress.py
  cron/eventStats.py
  cron/healthAndStatus.py
  cron/healthToMongo.py
  cron/okta2mozdef.py
  cron/sqs_queue_status.py
  cron/syncAlertsToMongo.py
  cron/verify_event_fields.py
  cron/vidyo2MozDef.py
Labels: Doc_type Removal

#1210 Fix docker tagging and add CI/CD docs
  CHANGELOG
  cloudy_mozdef/ci/docker_tag_or_push
  docs/source/cicd.rst
  docs/source/index.rst
Labels: category:bug, cloud

#1203 Remove doctype mozdefutil
  docs/source/mozdef_util/create.rst
  mozdef_util/mozdef_util/elasticsearch_client.py
  mozdef_util/mozdef_util/event.py
  tests/mozdef_util/query_models/test_search_query.py
  tests/mozdef_util/test_elasticsearch_client.py
  tests/unit_test_suite.py
Labels: Doc_type Removal

#1179 Update Elasticsearch6 docker container
  docker/compose/elasticsearch/Dockerfile
  docker/compose/elasticsearch/files/elasticsearch.yml
Labels: ES6 Breaking Changes

#1183 Remove doc_type from mq
  mq/esworker_cloudtrail.py
  mq/esworker_eventtask.py
  mq/esworker_papertrail.py
  mq/esworker_sns_sqs.py
  mq/esworker_sqs.py
  mq/plugins/auditdFixup.py
  mq/plugins/broFixup.py
  mq/plugins/complianceitems.py
  mq/plugins/customDocType.py
  mq/plugins/dropMessage.py
  mq/plugins/googleFixup.py
  mq/plugins/ipFixup.py
  mq/plugins/netflowFixup.py
  mq/plugins/parse_sshd.py
  mq/plugins/parse_su.py
  mq/plugins/squidFixup.py
  mq/plugins/suricataFixup.py
  mq/plugins/vidyoCallID.py
  mq/plugins/vulnerability.py
Labels: Doc_type Removal

#1106 Adding open and close abstraction for managing indexes
  CHANGELOG
  cron/closeIndices.conf
  cron/closeIndices.py
  cron/closeIndices.sh
  mozdef_util/HISTORY.rst
  mozdef_util/mozdef_util/elasticsearch_client.py
  mozdef_util/setup.py
  requirements.txt
  tests/mozdef_util/test_elasticsearch_client.py
Labels: category:enhancement

#1213 Fix pep8 doctype removal
  .flake8
  cron/correlateUserMacAddress.py
  cron/healthToMongo.py
  cron/syncAlertsToMongo.py
Labels: Doc_type Removal
